### ISSUE TITLE
Laravel 5.4 incompatibility

### ISSUE THREAD

**Issue by ddbx** [stayallive/authority-l5#5]
@stayallive Composer crashes on account of the now-deprecated 'share' method being used in the AuthorityL5ServiceProvider.php file on line 33.  The Laravel documentation recommends using the singleton method instead.

**Comment by stayallive** [comment]
You are correct. I will tag a 5.4 compatible release in a few hours!

**Comment by stayallive** [comment]
Just tagged `2.4.4` which should be compatible with L5.4. Enjoy 👍
